Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'

Options:
 test-before-installing: True
 require-passing-tests-on: ['Linux', 'FreeBSD']
